export default {
  'rutas-de-entrega:eliminar:id': 'rutas-de-entrega:eliminar:id',
  'rutas-de-entrega:buscar:contactos-de-ruta':
    'rutas-de-entrega:buscar:contactos-de-ruta',
  'rutas-de-entrega:buscar:id': 'rutas-de-entrega:buscar:id',
  'rutas-de-entrega:leer:todo': 'rutas-de-entrega:leer:todo',
  'rutas-de-entrega:crear-modificar': 'rutas-de-entrega:crear-modificar',
  'pedido:eliminar': 'pedido:eliminar',
  'pedido:modificar': 'pedido:modificar',
  'pedido:crear': 'pedido:crear',
  'pedido:buscar:usuario': 'pedido:buscar:usuario',
  'pedido:buscar:contacto': 'pedido:buscar:contacto',
  'pedido:buscar:id': 'pedido:buscar:id',
  'pedido:leer:todo': 'pedido:leer:todo',
  'programacionTransformacion:actualizarUbicacion':
    'programacionTransformacion:actualizarUbicacion',
  'programacionTransformacion:ordenesPorAsignar':
    'programacionTransformacion:ordenesPorAsignar',
  'programacionTransformacion:asignar': 'programacionTransformacion:asignar',
  'reportePersonalizadoAlmacenDeProduccion:eliminar':
    'reportePersonalizadoAlmacenDeProduccion:eliminar',
  'reportePersonalizadoAlmacenDeProduccion:modificar':
    'reportePersonalizadoAlmacenDeProduccion:modificar',
  'reportePersonalizadoAlmacenDeProduccion:leer:todo:termino':
    'reportePersonalizadoAlmacenDeProduccion:leer:todo:termino',
  'reportePersonalizadoAlmacenDeProduccion:leer:id':
    'reportePersonalizadoAlmacenDeProduccion:leer:id',
  'reportePersonalizadoAlmacenDeProduccion:leer:todo':
    'reportePersonalizadoAlmacenDeProduccion:leer:todo',
  'reportePersonalizadoAlmacenDeProduccion:crear':
    'reportePersonalizadoAlmacenDeProduccion:crear',
  'parametros:estacionesDeEscaneo': 'parametros:estacionesDeEscaneo',
  'parametros:departamentoTransformacion':
    'parametros:departamentoTransformacion',
  'parametros:procesosEspeciales': 'parametros:procesosEspeciales',
  'parametros:localizacionDeOrdenes': 'parametros:localizacionDeOrdenes',
  'empleado:ingreso:modificar': 'empleado:ingreso:modificar',
  'empleado:evento:eliminar': 'empleado:evento:eliminar',
  'empleado:evento:bono': 'empleado:evento:bono',
  'empleado:evento:amonestacion': 'empleado:evento:amonestacion',
  'empleado:evento:felicitacion': 'empleado:evento:felicitacion',
  'empleado:evento:castigo': 'empleado:evento:castigo',
  'empleado:evento:curso': 'empleado:evento:curso',
  'empleado:evento:vacaciones': 'empleado:evento:vacaciones',
  'empleado:evento:permiso:rechazar': 'empleado:evento:permiso:rechazar',
  'empleado:evento:permiso:autorizar': 'empleado:evento:permiso:autorizar',
  'empleado:evento:permiso': 'empleado:evento:permiso',
  'empleado:evento:estatusLaboral:incapacidad:maternidad':
    'empleado:evento:estatusLaboral:incapacidad:maternidad',
  'empleado:evento:estatusLaboral:incapacidad:riesgoDeTrabajo':
    'empleado:evento:estatusLaboral:incapacidad:riesgoDeTrabajo',
  'empleado:evento:estatusLaboral:incapacidad:enfermedadGeneral':
    'empleado:evento:estatusLaboral:incapacidad:enfermedadGeneral',
  'empleado:evento:estatusLaboral:reingreso':
    'empleado:evento:estatusLaboral:reingreso',
  'empleado:evento:estatusLaboral:baja': 'empleado:evento:estatusLaboral:baja',
  'empleado:evento:sueldo': 'empleado:evento:sueldo',
  'empleado:evento:puesto': 'empleado:evento:puesto',
  'empleado:eliminar': 'empleado:eliminar',
  'empleado:crear': 'empleado:crear',
  'empleado:leer:termino': 'empleado:leer:termino',
  'empleado:leer:id': 'empleado:leer:id',
  'empleado:leer:todo': 'empleado:leer:todo',
  'puesto:eliminar': 'puesto:eliminar',
  'XXXXX:multiplePuesto': 'XXXXX:multiplePuesto',
  'puesto:modificar': 'puesto:modificar',
  'puesto:crear': 'puesto:crear',
  'puesto:leer:termino': 'puesto:leer:termino',
  'puesto:leer:id': 'puesto:leer:id',
  'puesto:leer:todo': 'puesto:leer:todo',
  'area:eliminar': 'area:eliminar',
  'area:modificar': 'area:modificar',
  'area:leer:termino': 'area:leer:termino',
  'area:leer:id': 'area:leer:id',
  'area:leer:todo': 'area:leer:todo',
  'area:crear': 'area:crear',
  'curso:leer:tipoDeCurso:troncoComun': 'curso:leer:tipoDeCurso:troncoComun',
  'curso:eliminar': 'curso:eliminar',
  'curso:modificar': 'curso:modificar',
  'curso:leer:termino': 'curso:leer:termino',
  'curso:leer:id': 'curso:leer:id',
  'curso:leer:todo': 'curso:leer:todo',
  'curso:crear': 'curso:crear',
  'requisicion:estatus:actualizar': 'requisicion:estatus:actualizar',
  'requisicion:leer:todo': 'requisicion:leer:todo',
  'requisicion:leer:id': 'requisicion:leer:id',
  'requisicion:eliminar': 'requisicion:eliminar',
  'requisicion:modificar': 'requisicion:modificar',
  'requisicion:crear': 'requisicion:crear',
  'divisa:eliminar': 'divisa:eliminar',
  'divisa:modificar': 'divisa:modificar',
  'divisa:leer:termino': 'divisa:leer:termino',
  'divisa:leer:id': 'divisa:leer:id',
  'divisa:leer:todo': 'divisa:leer:todo',
  'divisa:crear': 'divisa:crear',
  'proveedor:rutas:agregar': 'proveedor:rutas:agregar',
  'proveedor:eliminar': 'proveedor:eliminar',
  'proveedor:modificar': 'proveedor:modificar',
  'proveedor:leer:termino': 'proveedor:leer:termino',
  'proveedor:leer:id': 'proveedor:leer:id',
  'proveedor:leer:todo': 'proveedor:leer:todo',
  'proveedor:crear': 'proveedor:crear',
  'articulo:eliminar': 'articulo:eliminar',
  'articulo:modificar': 'articulo:modificar',
  'articulo:reportes:existencias': 'articulo:reportes:existencias',
  'articulo:leer:termino': 'articulo:leer:termino',
  'articulo:leer:id': 'articulo:leer:id',
  'articulo:leer:todo': 'articulo:leer:todo',
  'articulo:crear': 'articulo:crear',
  'almacenDescripcion:eliminar': 'almacenDescripcion:eliminar',
  'almacenDescripcion:modificar': 'almacenDescripcion:modificar',
  'almacenDescripcion:crear': 'almacenDescripcion:crear',
  'almacenDescripcion:leer:termino': 'almacenDescripcion:leer:termino',
  'almacenDescripcion:leer:id': 'almacenDescripcion:leer:id',
  'almacenDescripcion:leer:todo': 'almacenDescripcion:leer:todo',
  'folio:liberarParaProduccion': 'folio:liberarParaProduccion',
  'folio:entregarARevision': 'folio:entregarARevision',
  'folio:retornarAlVendedor': 'folio:retornarAlVendedor',
  'folio:porEntregarAProduccion:vendedor':
    'folio:porEntregarAProduccion:vendedor',
  'folio:filtrar': 'folio:filtrar',
  'folio:reporte:paraRevision': 'folio:reporte:paraRevision',
  'folio:detalle:folio': 'folio:detalle:folio',
  'folio:detalle:pedido': 'folio:detalle:pedido',
  'folio:detalle:orden': 'folio:detalle:orden',
  'folio:modificar:senalarOrdenesImpresas':
    'folio:modificar:senalarOrdenesImpresas',
  'folio:modificar': 'folio:modificar',
  'folio:leer:id': 'folio:leer:id',
  'folio:crear': 'folio:crear',
  'folio:eliminar': 'folio:eliminar',
  'almacenDeProductoTerminado:consolidar:modelo':
    'almacenDeProductoTerminado:consolidar:modelo',
  'almacenProductoTerminado:leer:termino':
    'almacenProductoTerminado:leer:termino',
  'almacenDeProductoTerminado:leer:todo':
    'almacenDeProductoTerminado:leer:todo',
  'reportes:almacenDeProduccion:personalizado:id':
    'reportes:almacenDeProduccion:personalizado:id',
  'reportes:almacenDeProduccion:faltantes':
    'reportes:almacenDeProduccion:faltantes',
  'reportes:productoTerminado:faltes': 'reportes:productoTerminado:faltes',
  'maquina:leer:departamento': 'maquina:leer:departamento',
  'maquina:eliminar': 'maquina:eliminar',
  'maquina:modificar': 'maquina:modificar',
  'maquina:leer:termino': 'maquina:leer:termino',
  'maquina:leer:id': 'maquina:leer:id',
  'maquina:leer:todo': 'maquina:leer:todo',
  'maquina:crear': 'maquina:crear',
  'familiaDeProcesos:modificar': 'familiaDeProcesos:modificar',
  'familiaDeProcesos:eliminar': 'familiaDeProcesos:eliminar',
  'familiaDeProcesos:leer:termino': 'familiaDeProcesos:leer:termino',
  'familiaDeProcesos:leer:id': 'familiaDeProcesos:leer:id',
  'familiaDeProcesos:leer:todo': 'familiaDeProcesos:leer:todo',
  'familiaDeProcesos:crear': 'familiaDeProcesos:crear',
  'proceso:leer:multiple': 'proceso:leer:multiple',
  'proceso:eliminar': 'proceso:eliminar',
  'proceso:modificar': 'proceso:modificar',
  'proceso:leer:termino': 'proceso:leer:termino',
  'proceso:leer:id': 'proceso:leer:id',
  'proceso:leer:todo': 'proceso:leer:todo',
  'proceso:crear': 'proceso:crear',
  'departamento:leer:multiple': 'departamento:leer:multiple',
  'departamento:eliminar': 'departamento:eliminar',
  'departamento:modificar': 'departamento:modificar',
  'departamento:leer:termino': 'departamento:leer:termino',
  'departamento:leer:id': 'departamento:leer:id',
  'departamento:leer:todo': 'departamento:leer:todo',
  'departamento:crear': 'departamento:crear',
  'cliente:modificar': 'cliente:modificar',
  'cliente:eliminar': 'cliente:eliminar',
  'cliente:leer:termino': 'cliente:leer:termino',
  'cliente:leer:id': 'cliente:leer:id',
  'cliente:leer:todo': 'cliente:leer:todo',
  'cliente:crear': 'cliente:crear',
  'sku:lote:eliminar': 'sku:lote:eliminar',
  'sku:lote:movimiento:modificar': 'sku:lote:movimiento:modificar',
  'sku:lote:movimiento:transferir-entre-almacenes':
    'sku:lote:movimiento:transferir-entre-almacenes',
  'sku:lote:movimiento:Eliminar': 'sku:lote:movimiento:Eliminar',
  'sku:lote:movimiento:Agregar': 'sku:lote:movimiento:Agregar',
  'sku:lote:crear': 'sku:lote:crear',
  'sku:eliminar:etiqueta': 'sku:eliminar:etiqueta',
  'sku:eliminar': 'sku:eliminar',
  'sku:modificar:agregar-etiqueta': 'sku:modificar:agregar-etiqueta',
  'sku:modificar:stock-mimimo-maximo': 'sku:modificar:stock-mimimo-maximo',
  'sku:modificar': 'sku:modificar',
  'sku:leer:termino': 'sku:leer:termino',
  'sku:leer:id': 'sku:leer:id',
  'sku:leer:todo': 'sku:leer:todo',
  'sku:imagen:eliminar': 'sku:imagen:eliminar',
  'sku:imagen:agregar': 'sku:imagen:agregar',
  'sku:crear': 'sku:crear',
  SUPER_ADMIN: 'SUPER_ADMIN',
  'administrador:usuario:leer:todo:ligero':
    'administrador:usuario:leer:todo:ligero',
  'administrador:usuario:leer:id': 'administrador:usuario:leer:id',
  'administrador:usuario:leer:termino': 'administrador:usuario:leer:termino',
  'administrador:usuario:eliminar': 'administrador:usuario:eliminar',
  'administrador:usuario:crear': 'administrador:usuario:crear',
  'administrador:usuario:modificar:eliminar-permiso':
    'administrador:usuario:modificar:eliminar-permiso',
  'usuario:modificar:eliminar-imagen': 'usuario:modificar:eliminar-imagen',
  'usuario:modificar:agregar-imagen': 'usuario:modificar:agregar-imagen',
  'administrador:usuario:modificar:agregar-permisos':
    'administrador:usuario:modificar:agregar-permisos',
  'administrador:usuario:modificar:password':
    'administrador:usuario:modificar:password',
  'administrador:usuario:modificar': 'administrador:usuario:modificar',
  'administrador:usuario:leer': 'administrador:usuario:leer',
  login: 'login'
}
