export default {
  'menu:': 'menu:',
  login: 'login',
  'administrador:usuario:leer': 'administrador:usuario:leer',
  'usuario:modificar': 'usuario:modificar',
  'administrador:usuario:crear': 'administrador:usuario:crear',
  'administrador:usuario:eliminar': 'administrador:usuario:eliminar',
  'administrador:usuario:roles': 'administrador:usuario:roles',
  'administrador:usuario:leer:termino': 'administrador:usuario:leer:termino',
  SUPER_ADMIN: 'SUPER_ADMIN',
  'upload:tipo:id': 'upload:tipo:id',
  'imagenes:tipo:ver': 'imagenes:tipo:ver',
  'modeloCompleto:crear': 'modeloCompleto:crear',
  'modeloCompleto:leer:todo': 'modeloCompleto:leer:todo',
  'modeloCompleto:leer:id': 'modeloCompleto:leer:id',
  'modeloCompleto:leer:termino': 'modeloCompleto:leer:termino',
  'modeloCompleto:eliminar': 'modeloCompleto:eliminar',
  'modeloCompleto:modificar': 'modeloCompleto:modificar',
  'modeloCompleto:leer:transito': 'modeloCompleto:leer:transito',
  'modeloCompleto:stock:modificar': 'modeloCompleto:stock:modificar',
  'cliente:crear': 'cliente:crear',
  'cliente:leer:todo': 'cliente:leer:todo',
  'cliente:leer:id': 'cliente:leer:id',
  'cliente:leer:termino': 'cliente:leer:termino',
  'cliente:eliminar': 'cliente:eliminar',
  'cliente:modificar': 'cliente:modificar',
  'departamento:crear': 'departamento:crear',
  'departamento:leer:todo': 'departamento:leer:todo',
  'departamento:leer:id': 'departamento:leer:id',
  'departamento:leer:termino': 'departamento:leer:termino',
  'departamento:modificar': 'departamento:modificar',
  'departamento:eliminar': 'departamento:eliminar',
  'departamento:leer:multiple': 'departamento:leer:multiple',
  'proceso:crear': 'proceso:crear',
  'proceso:leer:todo': 'proceso:leer:todo',
  'proceso:leer:id': 'proceso:leer:id',
  'proceso:leer:termino': 'proceso:leer:termino',
  'proceso:modificar': 'proceso:modificar',
  'proceso:eliminar': 'proceso:eliminar',
  'proceso:leer:multiple': 'proceso:leer:multiple',
  'familiaDeProcesos:crear': 'familiaDeProcesos:crear',
  'familiaDeProcesos:leer:todo': 'familiaDeProcesos:leer:todo',
  'familiaDeProcesos:leer:id': 'familiaDeProcesos:leer:id',
  'familiaDeProcesos:leer:termino': 'familiaDeProcesos:leer:termino',
  'familiaDeProcesos:eliminar': 'familiaDeProcesos:eliminar',
  'familiaDeProcesos:modificar': 'familiaDeProcesos:modificar',
  'maquina:crear': 'maquina:crear',
  'maquina:leer:todo': 'maquina:leer:todo',
  'maquina:leer:id': 'maquina:leer:id',
  'maquina:leer:termino': 'maquina:leer:termino',
  'maquina:modificar': 'maquina:modificar',
  'maquina:eliminar': 'maquina:eliminar',
  'maquina:leer:departamento': 'maquina:leer:departamento',
  'modelo:crear': 'modelo:crear',
  'modelo:leer:todo': 'modelo:leer:todo',
  'modelo:leer:id': 'modelo:leer:id',
  'modelo:leer:termino': 'modelo:leer:termino',
  'modelo:eliminar': 'modelo:eliminar',
  'modelo:modificar': 'modelo:modificar',
  'tamano:crear': 'tamano:crear',
  'tamano:leer:todo': 'tamano:leer:todo',
  'tamano:leer:id': 'tamano:leer:id',
  'tamano:leer:termino': 'tamano:leer:termino',
  'tamano:eliminar': 'tamano:eliminar',
  'tamano:modificar': 'tamano:modificar',
  'color:crear': 'color:crear',
  'color:leer:todo': 'color:leer:todo',
  'color:leer:id': 'color:leer:id',
  'color:leer:termino': 'color:leer:termino',
  'color:eliminar': 'color:eliminar',
  'color:modificar': 'color:modificar',
  'terminado:crear': 'terminado:crear',
  'terminado:leer:todo': 'terminado:leer:todo',
  'terminado:leer:id': 'terminado:leer:id',
  'terminado:leer:termino': 'terminado:leer:termino',
  'terminado:eliminar': 'terminado:eliminar',
  'terminado:modificar': 'terminado:modificar',
  'reportes:productoTerminado:faltes': 'reportes:productoTerminado:faltes',
  'reportes:almacenDeProduccion:faltantes':
    'reportes:almacenDeProduccion:faltantes',
  'reportes:almacenDeProduccion:personalizado:id':
    'reportes:almacenDeProduccion:personalizado:id',
  'almacenDeProductoTerminado:leer:todo':
    'almacenDeProductoTerminado:leer:todo',
  'almacenProductoTerminado:leer:termino':
    'almacenProductoTerminado:leer:termino',
  'almacenDeProductoTerminado:consolidar:modelo':
    'almacenDeProductoTerminado:consolidar:modelo',
  'almacenDeProductoTerminado:lote:crear':
    'almacenDeProductoTerminado:lote:crear',
  'almacenDeProductoTerminado:lote:eliminar':
    'almacenDeProductoTerminado:lote:eliminar',
  'almacenDeProductoTerminado:lote:modificar':
    'almacenDeProductoTerminado:lote:modificar',
  'almacenDeProductoTerminado:devolucion':
    'almacenDeProductoTerminado:devolucion',
  'almacenDeProductoTerminado:salida': 'almacenDeProductoTerminado:salida',
  'folio:eliminar': 'folio:eliminar',
  'folio:crear': 'folio:crear',
  'folio:leer:id': 'folio:leer:id',
  'folio:modificar': 'folio:modificar',
  'folio:marcarComoImpreso': 'folio:marcarComoImpreso',
  'folio:modificar:senalarOrdenesImpresas':
    'folio:modificar:senalarOrdenesImpresas',
  'folio:detalle:orden': 'folio:detalle:orden',
  'folio:detalle:pedido': 'folio:detalle:pedido',
  'folio:detalle:folio': 'folio:detalle:folio',
  'folio:reporte:paraRevision': 'folio:reporte:paraRevision',
  'folio:filtrar': 'folio:filtrar',
  'folio:porEntregarAProduccion:vendedor':
    'folio:porEntregarAProduccion:vendedor',
  'folio:retornarAlVendedor': 'folio:retornarAlVendedor',
  'folio:entregarARevision': 'folio:entregarARevision',
  'folio:liberarParaProduccion': 'folio:liberarParaProduccion',
  'almacenDescripcion:leer:todo': 'almacenDescripcion:leer:todo',
  'almacenDescripcion:leer:id': 'almacenDescripcion:leer:id',
  'almacenDescripcion:leer:termino': 'almacenDescripcion:leer:termino',
  'almacenDescripcion:crear': 'almacenDescripcion:crear',
  'almacenDescripcion:modificar': 'almacenDescripcion:modificar',
  'almacenDescripcion:eliminar': 'almacenDescripcion:eliminar',
  'articulo:crear': 'articulo:crear',
  'articulo:leer:todo': 'articulo:leer:todo',
  'articulo:leer:id': 'articulo:leer:id',
  'articulo:leer:termino': 'articulo:leer:termino',
  'articulo:modificar': 'articulo:modificar',
  'articulo:eliminar': 'articulo:eliminar',
  'proveedor:crear': 'proveedor:crear',
  'proveedor:leer:todo': 'proveedor:leer:todo',
  'proveedor:leer:id': 'proveedor:leer:id',
  'proveedor:leer:termino': 'proveedor:leer:termino',
  'proveedor:modificar': 'proveedor:modificar',
  'proveedor:eliminar': 'proveedor:eliminar',
  'divisa:crear': 'divisa:crear',
  'divisa:leer:todo': 'divisa:leer:todo',
  'divisa:leer:id': 'divisa:leer:id',
  'divisa:leer:termino': 'divisa:leer:termino',
  'divisa:modificar': 'divisa:modificar',
  'divisa:eliminar': 'divisa:eliminar',
  'requisicion:crear': 'requisicion:crear',
  'requisicion:modificar': 'requisicion:modificar',
  'requisicion:eliminar': 'requisicion:eliminar',
  'requisicion:leer:id': 'requisicion:leer:id',
  'requisicion:leer:todo': 'requisicion:leer:todo',
  'requisicion:estatus:actualizar': 'requisicion:estatus:actualizar',
  'curso:crear': 'curso:crear',
  'curso:leer:todo': 'curso:leer:todo',
  'curso:leer:id': 'curso:leer:id',
  'curso:leer:termino': 'curso:leer:termino',
  'curso:modificar': 'curso:modificar',
  'curso:eliminar': 'curso:eliminar',
  'curso:leer:tipoDeCurso:troncoComun': 'curso:leer:tipoDeCurso:troncoComun',
  'area:crear': 'area:crear',
  'area:leer:todo': 'area:leer:todo',
  'area:leer:id': 'area:leer:id',
  'area:leer:termino': 'area:leer:termino',
  'area:modificar': 'area:modificar',
  'area:eliminar': 'area:eliminar',
  'puesto:leer:todo': 'puesto:leer:todo',
  'puesto:leer:id': 'puesto:leer:id',
  'puesto:leer:termino': 'puesto:leer:termino',
  'puesto:crear': 'puesto:crear',
  'puesto:modificar': 'puesto:modificar',
  'XXXXX:multiplePuesto': 'XXXXX:multiplePuesto',
  'puesto:eliminar': 'puesto:eliminar',
  'empleado:leer:todo': 'empleado:leer:todo',
  'empleado:leer:id': 'empleado:leer:id',
  'empleado:leer:termino': 'empleado:leer:termino',
  'empleado:crear': 'empleado:crear',
  'empleado:modificar': 'empleado:modificar',
  'empleado:eliminar': 'empleado:eliminar',
  'empleado:evento:puesto': 'empleado:evento:puesto',
  'empleado:evento:sueldo': 'empleado:evento:sueldo',
  'empleado:evento:estatusLaboral:baja': 'empleado:evento:estatusLaboral:baja',
  'empleado:evento:estatusLaboral:reingreso':
    'empleado:evento:estatusLaboral:reingreso',
  'empleado:evento:estatusLaboral:incapacidad:enfermedadGeneral':
    'empleado:evento:estatusLaboral:incapacidad:enfermedadGeneral',
  'empleado:evento:estatusLaboral:incapacidad:riesgoDeTrabajo':
    'empleado:evento:estatusLaboral:incapacidad:riesgoDeTrabajo',
  'empleado:evento:estatusLaboral:incapacidad:maternidad':
    'empleado:evento:estatusLaboral:incapacidad:maternidad',
  'empleado:evento:permiso': 'empleado:evento:permiso',
  'empleado:evento:permiso:autorizar': 'empleado:evento:permiso:autorizar',
  'empleado:evento:permiso:rechazar': 'empleado:evento:permiso:rechazar',
  'empleado:evento:vacaciones': 'empleado:evento:vacaciones',
  'empleado:evento:curso': 'empleado:evento:curso',
  'empleado:evento:castigo': 'empleado:evento:castigo',
  'empleado:evento:felicitacion': 'empleado:evento:felicitacion',
  'empleado:evento:amonestacion': 'empleado:evento:amonestacion',
  'empleado:evento:bono': 'empleado:evento:bono',
  'empleado:evento:eliminar': 'empleado:evento:eliminar',
  'reportePersonalizadoAlmacenDeProduccion:crear':
    'reportePersonalizadoAlmacenDeProduccion:crear',
  'reportePersonalizadoAlmacenDeProduccion:leer:todo':
    'reportePersonalizadoAlmacenDeProduccion:leer:todo',
  'reportePersonalizadoAlmacenDeProduccion:leer:id':
    'reportePersonalizadoAlmacenDeProduccion:leer:id',
  'reportePersonalizadoAlmacenDeProduccion:leer:todo:termino':
    'reportePersonalizadoAlmacenDeProduccion:leer:todo:termino',
  'reportePersonalizadoAlmacenDeProduccion:modificar':
    'reportePersonalizadoAlmacenDeProduccion:modificar',
  'reportePersonalizadoAlmacenDeProduccion:eliminar':
    'reportePersonalizadoAlmacenDeProduccion:eliminar',
  'programacionTransformacion:asignar': 'programacionTransformacion:asignar',
  'programacionTransformacion:desasignar':
    'programacionTransformacion:desasignar',
  'programacionTransformacion:ordenesPorAsignar':
    'programacionTransformacion:ordenesPorAsignar',
  'programacionTransformacion:actualizarUbicacion':
    'programacionTransformacion:actualizarUbicacion',
  'menu:reportes': 'menu:reportes',
  'menu:reportes:productoTerminado:faltantes':
    'menu:reportes:productoTerminado:faltantes',
  'menu:reportes:almacenDeProduccion:faltantes':
    'menu:reportes:almacenDeProduccion:faltantes',
  'menu:reportes:almacenDeProduccion:personalizado':
    'menu:reportes:almacenDeProduccion:personalizado',
  'menu:reportes:transformacion': 'menu:reportes:transformacion',
  'menu:almacen': 'menu:almacen',
  'menu:almacen:productoTerminado': 'menu:almacen:productoTerminado',
  'menu:almacen:produccion': 'menu:almacen:produccion',
  'menu:almacen:produccion:entradasYSalidas':
    'menu:almacen:produccion:entradasYSalidas',
  'menu:almacen:requisiciones': 'menu:almacen:requisiciones',
  'menu:almacen:reportesPersonalizados': 'menu:almacen:reportesPersonalizados',
  'menu:controlDeProduccion': 'menu:controlDeProduccion',
  'menu:controlDeProduccion:folios:revision':
    'menu:controlDeProduccion:folios:revision',
  'menu:controlDeProduccion:folios:seguimiento':
    'menu:controlDeProduccion:folios:seguimiento',
  'menu:controlDeProduccion:folios:asignarOrdenes':
    'menu:controlDeProduccion:folios:asignarOrdenes',
  'menu:ingenieria:': 'menu:ingenieria:',
  'menu:ingenieria:procesos': 'menu:ingenieria:procesos',
  'menu:ingenieria:familiaDeProcesos': 'menu:ingenieria:familiaDeProcesos',
  'menu:ingenieria:modelos': 'menu:ingenieria:modelos',
  'menu:ingenieria:tamanos': 'menu:ingenieria:tamanos',
  'menu:ingenieria:colores': 'menu:ingenieria:colores',
  'menu:ingenieria:terminados': 'menu:ingenieria:terminados',
  'menu:ingenieria:sku': 'menu:ingenieria:sku',
  'menu:ingenieria:maquinas': 'menu:ingenieria:maquinas',
  'menu:ventas': 'menu:ventas',
  'menu:ventas:misFolios': 'menu:ventas:misFolios',
  'menu:ventas:stock': 'menu:ventas:stock',
  'menu:proveedores': 'menu:proveedores',
  'menu:divisas': 'menu:divisas',
  'menu:administrador': 'menu:administrador',
  'menu:administrador:usuarios': 'menu:administrador:usuarios',
  'menu:administrador:departamentos': 'menu:administrador:departamentos',
  'menu:administrador:areas': 'menu:administrador:areas',
  'menu:administrador:clientes': 'menu:administrador:clientes',
  'menu:administrador:almacenDescripcion':
    'menu:administrador:almacenDescripcion',
  'menu:produccion': 'menu:produccion',
  'menu:produccion:almacenDeBoton': 'menu:produccion:almacenDeBoton',
  'menu:produccion:barnizado': 'menu:produccion:barnizado',
  'menu:produccion:burato': 'menu:produccion:burato',
  'menu:produccion:controlDeProduccion': 'menu:produccion:controlDeProduccion',
  'menu:produccion:empaque': 'menu:produccion:empaque',
  'menu:produccion:materiales': 'menu:produccion:materiales',
  'menu:produccion:pastilla': 'menu:produccion:pastilla',
  'menu:produccion:laser': 'menu:produccion:laser',
  'menu:produccion:metalizado': 'menu:produccion:metalizado',
  'menu:produccion:seleccion': 'menu:produccion:seleccion',
  'menu:produccion:transformacion': 'menu:produccion:transformacion',
  'menu:produccion:pulido': 'menu:produccion:pulido',
  'menu:produccion:productoTerminado': 'menu:produccion:productoTerminado',
  'menu:produccion:tenido': 'menu:produccion:tenido',
  'menu:rh': 'menu:rh',
  'menu:rh:empleados': 'menu:rh:empleados',
  'menu:rh:cursos': 'menu:rh:cursos',
  'menu:rh:puestos': 'menu:rh:puestos',
  'rol:vendedor': 'rol:vendedor',
  'rol:contadorBoton': 'rol:contadorBoton',
  'rol:empacador': 'rol:empacador',
  'rol:cargadorMaterial': 'rol:cargadorMaterial'
}
