export default {
  'parametros:version-offline-reiniciar': 'Reinicia el versionado offline',
  'menu:configuraciones:contactos': '',
  'menu:configuraciones:rutas-de-entrega':
    'Ver el menu de parametros de ruta de entrega',
  'menu:configuraciones:parametros': 'Ver el menu de parametros',
  'menu:configuraciones:usuarios':
    'Ver el menu de usuarios dentro del menu administrador',
  'menu:ventas:listas-de-precios': '',
  'menu:ventas:mis-pedidos': '',
  'menu:ventas': 'Ver el menu de ventas',
  'menu:almacen:sku': 'Menu de gestion general del almacen',
  'menu:almacen': 'Mostrar el menu de almacen',
  'lista-de-precios:eliminar': 'Sin descripción',
  'lista-de-precios:asignar-a-acliente': 'Sin descripción',
  'lista-de-precios:modificar:id': 'Sin descripción',
  'lista-de-precios:leer:id': 'Leer las listas de precio existentes',
  'lista-de-precios:leer:todo:ligero':
    'Leer las listas de precio existentes para asignar a un contacto',
  'lista-de-precios:leer:todo': 'Leer las listas de precio existentes',
  'lista-de-precios:crear': 'Crear una nueva lista de precios',
  'contabilidad:remision:leer:todo': 'Leer todas las remisiones',
  'contabilidad:remision:crear': 'Crear una nueva remision',
  'usuario:modificar:eliminar-imagen': 'Elimina la imagen del usuario',
  'rutas-de-entrega:eliminar:id': 'Eliminar una ruta por su id',
  'rutas-de-entrega:buscar:contactos-de-ruta':
    'Buscar todos los cantactos asignados a una ruta',
  'rutas-de-entrega:buscar:id': 'Buscar por id una ruta',
  'rutas-de-entrega:leer:todo': 'Leer todas las rutas existentes',
  'rutas-de-entrega:crear-modificar': 'Crear o modificar una ruta de entrega',
  'estadisticas:total-contactos': 'Muestra el total de los contactos',
  'estadisticas:total-costo-existencias':
    'Muestra el costo total de las existencias',
  'estadisticas:total-skus': 'Muestra el total de elementos en el dashboard',
  'configuraciones:usuarios:administrar':
    'Administrar las configuraciones generales de usuarios como carga por lotes',
  'configuraciones:contactos:administrar':
    'Administrar las configuraciones generales de contactos como carga por lotes',
  'configuraciones:skus:administrar':
    'Administrar las configuraciones generales de los skus como carga por lote',
  'configuraciones:lista-de-precios:administrar':
    'Administrar las configuraciones generales de listas de precios como la carga por lotes y listas por default.',
  'configuraciones:etiquetas:eliminar':
    'Eliminar una etiqueta de la lista de autocompletado',
  'contacto:rutas:agregar': 'Agregar rutas a un contacto',
  'contacto:eliminar': 'Sin descripción',
  'contacto:modificar': 'Sin descripción',
  'contacto:leer:termino': 'Sin descripción',
  'contacto:leer:id': 'Sin descripción',
  'contacto:leer:todo': 'Sin descripción',
  'contacto:crear': 'Sin descripción',
  'sku:lote:eliminar': 'Eliminar lotes completamente',
  'sku:lote:movimiento:modificar': 'Modificar un movimento existente',
  'sku:lote:movimiento:transferir-entre-almacenes':
    'Hacer transfericias entre dos almacenes.',
  'sku:lote:movimiento:Eliminar': 'Eliminar movimentos de un lote',
  'sku:lote:movimiento:Agregar': 'Agregar entradas o salidas a un lote.',
  'sku:lote:crear': 'Crear lotes nuevos',
  'sku:eliminar:etiqueta': 'Sin descripción',
  'sku:eliminar': 'Sin descripción',
  'sku:modificar:agregar-etiqueta': 'Sin descripción',
  'sku:modificar:stock-mimimo-maximo': 'Modificar el stock minimo y maximo',
  'sku:modificar': 'Modificar sku',
  'sku:leer:termino': 'Sin descripción',
  'sku:leer:id': 'Obtiene un sku por su id',
  'sku:leer:todo:lista-de-precios': 'Leer todos los sku registrados en la BD',
  'sku:leer:todo': 'Muestra los datos generales de los sku',
  'sku:imagen:eliminar': 'Eliminar una imagen del sku',
  'sku:imagen:agregar': 'Agregar una imagen al SKU',
  'sku:crear': 'Crea un nuevo SKU',
  'usuario:modificar:inhabilitar': 'Deshabilita al usuario ',
  'usuario:modificar:eliminar-permiso': 'Elimina un permiso del usuario',
  'usuario:modificar:agregar-permiso': 'Crea un nuevo permiso al usuario',
  'usuario:crear': 'Crear un nuevo usuario',
  login: 'Iniciar sesión en el sistema',
  'usuario:leer:todo': 'Leer todos los usuarios registrados en el sistema. ',
  administrador: 'Permisos de administrador'
}
