export default {
  "login":"false",
  "menu:compras:proveedores":"false",
  "menu:compras":"false",
  "menu:almacen:sku":"false",
  "menu:almacen":"false",
  "programacionTransformacion:actualizarUbicacion":"Sin descripcion",
  "programacionTransformacion:ordenesPorAsignar":"Sin descripcion",
  "programacionTransformacion:asignar":"Sin descripcion",
  "reportePersonalizadoAlmacenDeProduccion:eliminar":"Sin descripcion",
  "reportePersonalizadoAlmacenDeProduccion:modificar":"Sin descripcion",
  "reportePersonalizadoAlmacenDeProduccion:leer:todo:termino":"Sin descripcion",
  "reportePersonalizadoAlmacenDeProduccion:leer:id":"Sin descripcion",
  "reportePersonalizadoAlmacenDeProduccion:leer:todo":"Sin descripcion",
  "reportePersonalizadoAlmacenDeProduccion:crear":"Sin descripcion",
  "parametros:estacionesDeEscaneo":"Sin descripcion",
  "parametros:departamentoTransformacion":"Sin descripcion",
  "parametros:procesosEspeciales":"Sin descripcion",
  "parametros:localizacionDeOrdenes":"Sin descripcion",
  "empleado:ingreso:modificar":"Sin descripcion",
  "empleado:evento:eliminar":"Sin descripcion",
  "empleado:evento:bono":"Sin descripcion",
  "empleado:evento:amonestacion":"Sin descripcion",
  "empleado:evento:felicitacion":"Sin descripcion",
  "empleado:evento:castigo":"Sin descripcion",
  "empleado:evento:curso":"Sin descripcion",
  "empleado:evento:vacaciones":"Sin descripcion",
  "empleado:evento:permiso:rechazar":"Sin descripcion",
  "empleado:evento:permiso:autorizar":"Sin descripcion",
  "empleado:evento:permiso":"Sin descripcion",
  "empleado:evento:estatusLaboral:incapacidad:maternidad":"Sin descripcion",
  "empleado:evento:estatusLaboral:incapacidad:riesgoDeTrabajo":"Sin descripcion",
  "empleado:evento:estatusLaboral:incapacidad:enfermedadGeneral":"Sin descripcion",
  "empleado:evento:estatusLaboral:reingreso":"Sin descripcion",
  "empleado:evento:estatusLaboral:baja":"Sin descripcion",
  "empleado:evento:sueldo":"Sin descripcion",
  "empleado:evento:puesto":"Sin descripcion",
  "empleado:eliminar":"Sin descripcion",
  "empleado:crear":"Sin descripcion",
  "empleado:leer:termino":"Sin descripcion",
  "empleado:leer:id":"Sin descripcion",
  "empleado:leer:todo":"Sin descripcion",
  "puesto:eliminar":"Sin descripcion",
  "XXXXX:multiplePuesto":"Sin descripcion",
  "puesto:modificar":"Sin descripcion",
  "puesto:crear":"Sin descripcion",
  "puesto:leer:termino":"Sin descripcion",
  "puesto:leer:id":"Sin descripcion",
  "puesto:leer:todo":"Sin descripcion",
  "area:eliminar":"Sin descripcion",
  "area:modificar":"Sin descripcion",
  "area:leer:termino":"Sin descripcion",
  "area:leer:id":"Sin descripcion",
  "area:leer:todo":"Sin descripcion",
  "area:crear":"Sin descripcion",
  "curso:leer:tipoDeCurso:troncoComun":"Sin descripcion",
  "curso:eliminar":"Sin descripcion",
  "curso:modificar":"Sin descripcion",
  "curso:leer:termino":"Sin descripcion",
  "curso:leer:id":"Sin descripcion",
  "curso:leer:todo":"Sin descripcion",
  "curso:crear":"Sin descripcion",
  "requisicion:estatus:actualizar":"Sin descripcion",
  "requisicion:leer:todo":"Sin descripcion",
  "requisicion:leer:id":"Sin descripcion",
  "requisicion:eliminar":"Sin descripcion",
  "requisicion:modificar":"Sin descripcion",
  "requisicion:crear":"Sin descripcion",
  "divisa:eliminar":"Sin descripcion",
  "divisa:modificar":"Sin descripcion",
  "divisa:leer:termino":"Sin descripcion",
  "divisa:leer:id":"Sin descripcion",
  "divisa:leer:todo":"Sin descripcion",
  "divisa:crear":"Sin descripcion",
  "proveedor:eliminar":"Sin descripcion",
  "proveedor:modificar":"Sin descripcion",
  "proveedor:leer:termino":"Sin descripcion",
  "proveedor:leer:id":"Sin descripcion",
  "proveedor:leer:todo":"Sin descripcion",
  "proveedor:crear":"Sin descripcion",
  "articulo:eliminar":"Sin descripcion",
  "articulo:modificar":"Sin descripcion",
  "articulo:reportes:existencias":"Sin descripcion",
  "articulo:leer:termino":"Sin descripcion",
  "articulo:leer:id":"Sin descripcion",
  "articulo:leer:todo":"Sin descripcion",
  "articulo:crear":"Sin descripcion",
  "almacenDescripcion:eliminar":"Sin descripcion",
  "almacenDescripcion:modificar":"Sin descripcion",
  "almacenDescripcion:crear":"Sin descripcion",
  "almacenDescripcion:leer:termino":"Sin descripcion",
  "almacenDescripcion:leer:id":"Sin descripcion",
  "almacenDescripcion:leer:todo":"Sin descripcion",
  "folio:liberarParaProduccion":"Sin descripcion",
  "folio:entregarARevision":"Sin descripcion",
  "folio:retornarAlVendedor":"Sin descripcion",
  "folio:porEntregarAProduccion:vendedor":"Sin descripcion",
  "folio:filtrar":"Sin descripcion",
  "folio:reporte:paraRevision":"Sin descripcion",
  "folio:detalle:folio":"Sin descripcion",
  "folio:detalle:pedido":"Sin descripcion",
  "folio:detalle:orden":"Sin descripcion",
  "folio:modificar:senalarOrdenesImpresas":"Sin descripcion",
  "folio:modificar":"Sin descripcion",
  "folio:leer:id":"Sin descripcion",
  "folio:crear":"Sin descripcion",
  "folio:eliminar":"Sin descripcion",
  "almacenDeProductoTerminado:consolidar:modelo":"Sin descripcion",
  "almacenProductoTerminado:leer:termino":"Sin descripcion",
  "almacenDeProductoTerminado:leer:todo":"Sin descripcion",
  "reportes:almacenDeProduccion:personalizado:id":"Sin descripcion",
  "reportes:almacenDeProduccion:faltantes":"Sin descripcion",
  "reportes:productoTerminado:faltes":"Sin descripcion",
  "maquina:leer:departamento":"Sin descripcion",
  "maquina:eliminar":"Sin descripcion",
  "maquina:modificar":"Sin descripcion",
  "maquina:leer:termino":"Sin descripcion",
  "maquina:leer:id":"Sin descripcion",
  "maquina:leer:todo":"Sin descripcion",
  "maquina:crear":"Sin descripcion",
  "familiaDeProcesos:modificar":"Sin descripcion",
  "familiaDeProcesos:eliminar":"Sin descripcion",
  "familiaDeProcesos:leer:termino":"Sin descripcion",
  "familiaDeProcesos:leer:id":"Sin descripcion",
  "familiaDeProcesos:leer:todo":"Sin descripcion",
  "familiaDeProcesos:crear":"Sin descripcion",
  "proceso:leer:multiple":"Sin descripcion",
  "proceso:eliminar":"Sin descripcion",
  "proceso:modificar":"Sin descripcion",
  "proceso:leer:termino":"Sin descripcion",
  "proceso:leer:id":"Sin descripcion",
  "proceso:leer:todo":"Sin descripcion",
  "proceso:crear":"Sin descripcion",
  "departamento:leer:multiple":"Sin descripcion",
  "departamento:eliminar":"Sin descripcion",
  "departamento:modificar":"Sin descripcion",
  "departamento:leer:termino":"Sin descripcion",
  "departamento:leer:id":"Sin descripcion",
  "departamento:leer:todo":"Sin descripcion",
  "departamento:crear":"Sin descripcion",
  "cliente:modificar":"Sin descripcion",
  "cliente:eliminar":"Sin descripcion",
  "cliente:leer:termino":"Sin descripcion",
  "cliente:leer:id":"Sin descripcion",
  "cliente:leer:todo":"Sin descripcion",
  "cliente:crear":"Sin descripcion",
  "sku:lote:eliminar":"Eliminar lotes completamente",
  "sku:lote:movimiento:modificar":"Modificar un movimento existente",
  "sku:lote:movimiento:transferir-entre-almacenes":"Hacer transfericias entre dos almacenes.",
  "sku:lote:movimiento:Eliminar":"Eliminar movimentos de un lote",
  "sku:lote:movimiento:Agregar":"Agregar entradas o salidas a un lote.",
  "sku:lote:crear":"Crear lotes nuevos",
  "sku:eliminar:etiqueta":"Sin descripcion",
  "sku:eliminar":"Sin descripcion",
  "sku:modificar:agregar-etiqueta":"Sin descripcion",
  "sku:modificar:stock-mimimo-maximo":"Modificar el stock minimo y maximo",
  "sku:modificar":"Modificar sku",
  "sku:leer:termino":"Sin descripcion",
  "sku:leer:id":"Obtiene un sku por su id",
  "sku:leer:todo":"Muestra los datos generales de los sku",
  "sku:imagen:eliminar":"Eliminar una imagen del sku",
  "sku:imagen:agregar":"Agregar una imagen al SKU",
  "sku:crear":"Crea un nuevo SKU",
  "SUPER_ADMIN":"Sin descripcion",
  "administrador:usuario:leer:todo:ligero":"Obtener todos los usuarios solo con los datos más basicos. ",
  "administrador:usuario:leer:id":"Buscar un usuario por su id",
  "administrador:usuario:leer:termino":"Buscar un usuario por un termino de busqueda",
  "administrador:usuario:eliminar":"Eliminar un usuario",
  "administrador:usuario:crear":"Crear un usuario",
  "administrador:usuario:modificar:eliminar-permiso":"Eliminar permisos de un usuario",
  "usuario:modificar:eliminar-imagen":"Elimina la imagen del usuario",
  "usuario:modificar:agregar-imagen":"Agregar una imagen al usuario",
  "administrador:usuario:modificar:agregar-permisos":"Agregar permisos a un usuario",
  "administrador:usuario:modificar:password":"Modificar el password de un usuario",
  "administrador:usuario:modificar":"Modificar datos basicos de un usuario",
  "administrador:usuario:leer":"Leer los usuarios existentes",

}
