export default {
  'lista-de-precios:leer:todo:ligero': 'lista-de-precios:leer:todo:ligero',
  'contacto:rutas:agregar': 'contacto:rutas:agregar',
  'contacto:crear': 'contacto:crear',
  'contacto:eliminar': 'contacto:eliminar',
  'contacto:modificar': 'contacto:modificar',
  'contacto:leer:termino': 'contacto:leer:termino',
  'contacto:leer:id': 'contacto:leer:id',
  'contacto:leer:todo': 'contacto:leer:todo',
  'menu:administrador:contactos': 'menu:administrador:contactos',
  'menu:administrador:clientes': 'menu:administrador:clientes',
  'menu:ventas:clientes': 'menu:ventas:clientes',
  'sku:leer:todo:lista-de-precios': 'sku:leer:todo:lista-de-precios',
  'menu:ventas:listas-de-precios': 'menu:ventas:listas-de-precios',
  'lista-de-precios:eliminar': 'lista-de-precios:eliminar',
  'lista-de-precios:asignar-a-acliente': 'lista-de-precios:asignar-a-acliente',
  'lista-de-precios:modificar:id': 'lista-de-precios:modificar:id',
  'lista-de-precios:leer:id': 'lista-de-precios:leer:id',
  'lista-de-precios:leer:todo': 'lista-de-precios:leer:todo',
  'lista-de-precios:crear': 'lista-de-precios:crear',
  'lista-de-precios:': 'lista-de-precios:',
  'menu:contabilidad:facturas': 'menu:contabilidad:facturas',
  'menu:contabilidad:remisiones': 'menu:contabilidad:remisiones',
  'menu:contabilidad:tablero-contable': 'menu:contabilidad:tablero-contable',
  'menu:contabilidad': 'menu:contabilidad',
  'menu:venta-al-publico:punto-de-venta':
    'menu:venta-al-publico:punto-de-venta',
  'menu:venta-al-publico': 'menu:venta-al-publico',
  'menu:administrador:rutas-de-entrega': 'menu:administrador:rutas-de-entrega',
  'menu:administrador:parametros': 'menu:administrador:parametros',
  'menu:administrador:usuarios': 'menu:administrador:usuarios',
  'menu:administrador': 'menu:administrador',
  'menu:compras:contactos': 'menu:compras:contactos',
  'menu:compras': 'menu:compras',
  'menu:ventas:mis-pedidos': 'menu:ventas:mis-pedidos',
  'menu:ventas': 'menu:ventas',
  'menu:almacen:sku': 'menu:almacen:sku',
  'menu:almacen': 'menu:almacen',
  'contabilidad:remision:leer:todo': 'contabilidad:remision:leer:todo',
  'contabilidad:remision:crear': 'contabilidad:remision:crear',
  'usuario:modificar:eliminar-imagen': 'usuario:modificar:eliminar-imagen',
  'rutas-de-entrega:eliminar:id': 'rutas-de-entrega:eliminar:id',
  'rutas-de-entrega:buscar:contactos-de-ruta':
    'rutas-de-entrega:buscar:contactos-de-ruta',
  'rutas-de-entrega:buscar:id': 'rutas-de-entrega:buscar:id',
  'rutas-de-entrega:leer:todo': 'rutas-de-entrega:leer:todo',
  'rutas-de-entrega:crear-modificar': 'rutas-de-entrega:crear-modificar',
  'proveedor:rutas:agregar': 'proveedor:rutas:agregar',
  'proveedor:eliminar': 'proveedor:eliminar',
  'proveedor:modificar': 'proveedor:modificar',
  'proveedor:leer:termino': 'proveedor:leer:termino',
  'proveedor:leer:id': 'proveedor:leer:id',
  'proveedor:leer:todo': 'proveedor:leer:todo',
  'proveedor:crear': 'proveedor:crear',
  'sku:lote:eliminar': 'sku:lote:eliminar',
  'sku:lote:movimiento:modificar': 'sku:lote:movimiento:modificar',
  'sku:lote:movimiento:transferir-entre-almacenes':
    'sku:lote:movimiento:transferir-entre-almacenes',
  'sku:lote:movimiento:Eliminar': 'sku:lote:movimiento:Eliminar',
  'sku:lote:movimiento:Agregar': 'sku:lote:movimiento:Agregar',
  'sku:lote:crear': 'sku:lote:crear',
  'sku:eliminar:etiqueta': 'sku:eliminar:etiqueta',
  'sku:eliminar': 'sku:eliminar',
  'sku:modificar:agregar-etiqueta': 'sku:modificar:agregar-etiqueta',
  'sku:modificar:stock-mimimo-maximo': 'sku:modificar:stock-mimimo-maximo',
  'sku:modificar': 'sku:modificar',
  'sku:leer:termino': 'sku:leer:termino',
  'sku:leer:id': 'sku:leer:id',
  'sku:leer:todo': 'sku:leer:todo',
  'sku:imagen:eliminar': 'sku:imagen:eliminar',
  'sku:imagen:agregar': 'sku:imagen:agregar',
  'sku:crear': 'sku:crear',
  'usuario:modificar:inhabilitar': 'usuario:modificar:inhabilitar',
  'usuario:modificar:eliminar-permiso': 'usuario:modificar:eliminar-permiso',
  'usuario:modificar:agregar-permiso': 'usuario:modificar:agregar-permiso',
  'usuario:crear': 'usuario:crear',
  login: 'login',
  'usuario:leer:todo': 'usuario:leer:todo',
  administrador: 'administrador'
}
