
export const _ROLES = {

    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN_ROLE: 'ADMIN_ROLE',
    USER_ROLE: 'USER_ROLE',
    
    CONTROL_DE_PRODUCCION_REGISTRAR_FOLIOS_ROLE: 'CONTROL_DE_PRODUCCION_REGISTRAR_FOLIOS_ROLE',
    CONTROL_DE_PRODUCCION_CONSULTAR_FOLIOS_ROLE: 'CONTROL_DE_PRODUCCION_CONSULTAR_FOLIOS_ROLE',
    
    VENDEDOR_ADMIN_ROLE: 'VENDEDOR_ADMIN_ROLE',
    VENDEDOR_ROLE: 'VENDEDOR_ROLE',
    VENDEDOR_CONSULTA_ROLE: 'VENDEDOR_CONSULTA_ROLE',
    
    MATERIALES_REGISTRO_ROLE: 'MATERIALES_REGISTRO_ROLE',
    MATERIALES_CARGA_ROLE: 'MATERIALES_CARGA_ROLE',
    
    PASTILLA_REGISTRO_ROLE: 'PASTILLA_REGISTRO_ROLE',
    TRANSFORMACION_REGISTRO_ROLE: 'TRANSFORMACION_REGISTRO_ROLE',
    PULIDO_REGISTRO_ROLE: 'PULIDO_REGISTRO_ROLE',
    
    SELECCION_REGISTRO_ROLE: 'SELECCION_REGISTRO_ROLE',
    SELECCION_CONTEO_ROLE: 'SELECCION_CONTEO_ROLE',
    
    EMPAQUE_REGISTRO_ROLE: 'EMPAQUE_REGISTRO_ROLE',
    EMPAQUE_EMPACADOR_ROLE: 'EMPAQUE_EMPACADOR_ROLE',
     
};
